language: node_js
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '8'
script:
- yarn prettier-check
after_success:
- yarn semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: gae
  keyfile: gce.json
  project: flippa-35259
  verbosity: debug
  on: mvp 
before_install:
- openssl aes-256-cbc -K $encrypted_18339f154d6a_key -iv $encrypted_18339f154d6a_iv
  -in gce.json.enc -out gce.json -d
